all: 
  db: &db_defaults 
    host: localhost
    port: 27017
    name: dharma_api

test:
  db:
    <<: *db_defaults
    name: test

development:
  db:
    <<: *db_defaults

production:
  db:
    name: dharma_api
    host: ds033477.mongolab.com
    port: 33477

